In [2]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

print(f"version numpy: {np.__version__}")
print(f"version pandas: {pd.__version__}")
print(f"version sklearn: {sklearn.__version__}")

version numpy: 2.0.2
version pandas: 2.2.2
version sklearn: 1.6.1

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Synoris Training/Day4_training/Titanic_Data.csv")
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0          892         0       3  ...   7.8292   NaN         Q
1          893         1       3  ...   7.0000   NaN         S
2          894         0       2  ...   9.6875   NaN         Q
3          895         0       3  ...   8.6625   NaN         S
4          896         1       3  ...  12.2875   NaN         S

[5 rows x 12 columns]

In [4]:
df.describe()

       PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   418.000000  418.000000  418.000000  ...  418.000000  418.000000  417.000000
mean   1100.500000    0.363636    2.265550  ...    0.447368    0.392344   35.627188
std     120.810458    0.481622    0.841838  ...    0.896760    0.981429   55.907576
min     892.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     996.250000    0.000000    1.000000  ...    0.000000    0.000000    7.895800
50%    1100.500000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%    1204.750000    1.000000    3.000000  ...    1.000000    0.000000   31.500000
max    1309.000000    1.000000    3.000000  ...    8.000000    9.000000  512.329200

[8 rows x 7 columns]

In [8]:
df.corr(numeric_only=True)

             PassengerId  Survived    Pclass  ...     SibSp     Parch      Fare
PassengerId     1.000000 -0.023245 -0.026751  ...  0.003818  0.043080  0.008211
Survived       -0.023245  1.000000 -0.108615  ...  0.099943  0.159120  0.191514
Pclass         -0.026751 -0.108615  1.000000  ...  0.001087  0.018721 -0.577147
Age            -0.034102 -0.000013 -0.492143  ... -0.091587 -0.061249  0.337932
SibSp           0.003818  0.099943  0.001087  ...  1.000000  0.306895  0.171539
Parch           0.043080  0.159120  0.018721  ...  0.306895  1.000000  0.230046
Fare            0.008211  0.191514 -0.577147  ...  0.171539  0.230046  1.000000

[7 rows x 7 columns]

In [9]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0          892         0       3  ...   7.8292   NaN         Q
1          893         1       3  ...   7.0000   NaN         S
2          894         0       2  ...   9.6875   NaN         Q
3          895         0       3  ...   8.6625   NaN         S
4          896         1       3  ...  12.2875   NaN         S

[5 rows x 12 columns]

In [10]:
df = df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"])
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

In [11]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [12]:
df['Age'] = df['Age'].fillna(df.groupby('Sex')['Age'].transform('median'))
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        1
Embarked    0
dtype: int64

In [14]:
df.nunique()

Survived      2
Pclass        3
Sex           2
Age          79
SibSp         7
Parch         8
Fare        169
Embarked      3
dtype: int64

In [15]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [16]:
df['Fare'] = df['Fare'].fillna(df['Fare'].median())

df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

X = df.drop('Survived', axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(random_state=42, solver='liblinear') # Using 'liblinear' solver for small datasets and binary classification
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

Model Accuracy: 1.0000

In [17]:
import pickle
from google.colab import files

# Save the model to a .pkl file
filename = 'titanic_logistic_regression_model.pkl'
pickle.dump(model, open(filename, 'wb'))

# Download the file
files.download(filename)